### ISSUE TITLE
无法保存

### ISSUE THREAD

**Issue by TIKICJ** [abevol/InfectionFreeZoneMod#1]
ESC也保存不了

**Comment by abevol** [comment]
可以保存呀，只是没有提醒罢了，其实已经保存了。
重启游戏后，点击大厅里的加载游戏，即可重新进入之前保存的游戏。
后面我给加个提醒。

![保存游戏](https://github.com/abevol/InfectionFreeZoneMod/assets/85929368/de449660-039e-4320-8e61-8cf037877cce)
![加载游戏](https://github.com/abevol/InfectionFreeZoneMod/assets/85929368/02a674f6-dad4-49ed-8676-05f5215feaa7)

**Comment by abevol** [comment]
已添加游戏保存完成的提醒。
下个版本一起发布。

![游戏已保存](https://github.com/abevol/InfectionFreeZoneMod/assets/85929368/2f6ed6f7-d477-482b-a365-ab38cd697d4b)

**Comment by TIKICJ** [comment]
牛逼牛逼牛逼
