### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by TIKICJ** [abevol/InfectionFreeZoneMod#2]
新的问题，保存完，加载以后就不能招募小队了

**Comment by abevol** [comment]
![QQ截图20230802191528](https://github.com/abevol/InfectionFreeZoneMod/assets/85929368/ba75910a-f871-4b86-96f2-dc4e91b4215d)

你说的是这个总部里的创建新小队吧，我试了可以呀

**Comment by TIKICJ** [comment]
我的总感觉有些奇怪，MOD现在运行不了了

**Comment by TIKICJ** [comment]
之前是开游戏先弹一个对话框，然后进游戏，现在打开是直接进游戏，MOD没效果了

**Comment by abevol** [comment]
现在MOD有效果了吗？

**Comment by abevol** [comment]
问题发起人长时间未回复
