### ISSUE TITLE
日志精简

### ISSUE THREAD

**Issue by ZhReimu** [abevol/InfectionFreeZoneMod#4]
event_demo_end 这个日志就没必要打这么多次的，打多了浪费占用性能，而且日志文件还会很大
![image](https://github.com/abevol/InfectionFreeZoneMod/assets/58155247/13947334-e89b-4f31-a329-4fbb493adae0)

**Comment by abevol** [comment]
这个事件是demo版8天强制结束的事件，序章版已经没有这个事件，应该不会打印这个事件，更不可能会打印这么多次，你有改动过游戏的事件文件吗？

**Comment by ZhReimu** [comment]
应该是没有改过的, 而且序章版已经没有 EventsSystems 文件夹了
![image](https://github.com/abevol/InfectionFreeZoneMod/assets/58155247/fc770767-1aaf-4625-9db1-7d23fabc03f4)
今早又启动了下, 估计是存档有问题了
![image](https://github.com/abevol/InfectionFreeZoneMod/assets/58155247/d3ccfba7-3235-4bb2-882f-f6b70f13211c)
[Saves.zip](https://github.com/abevol/InfectionFreeZoneMod/files/13064829/Saves.zip)
有部分错误日志没有输出到文件, 我就粘在这里了
```log
[Message:    无感染区模组] StartEvent: event_demo_end
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Controllers.Weather.WeatherController.Sunset () (at <b5399e55b46140838ff3499e82f9f3fa>:0)
Controllers.Time.TimeController.CheckIfSunset () (at <b5399e55b46140838ff3499e82f9f3fa>:0)
Controllers.Time.TimeController.Update () (at <b5399e55b46140838ff3499e82f9f3fa>:0)
GameManager.CustomUpdate () (at <b5399e55b46140838ff3499e82f9f3fa>:0)
UpdateController.Update () (at <b5399e55b46140838ff3499e82f9f3fa>:0)
```
[LogOutput.log](https://github.com/abevol/InfectionFreeZoneMod/files/13064831/LogOutput.log)

**Comment by abevol** [comment]
官方这个老六把事件系统打包到`resources.assets`文件了，但即便如此也不应该打印这么多次。
对比了事件的代码也和Demo版本的一样，就很奇怪，我可以先把这个事件的打印给过滤掉。
谢谢你提供的存档文件！对我帮助很大，我看看能不能把这个崩溃的问题也解决了。

**Comment by abevol** [comment]
崩溃的问题已经修好了，你看看建筑物完整不
![QQ截图20231023150450](https://github.com/abevol/InfectionFreeZoneMod/assets/85929368/21873855-6fb8-4913-b3fb-1cb2f0ac7aab)

**Comment by ZhReimu** [comment]
可以的，能读档了, event_demo_end 的日志也没了
